extends:
  - standard

rules:
  # XXX ignore for now:
  no-undef: off
  # disable quotes for now, at least
  # FUTURE TBD decide whether to enforce single quotes
  # (as specified by "Standard JS") or
  # switch to using backticks instead
  quotes: off

  semi:
    - error
    - always

  comma-dangle:
    - error
    - arrays: only-multiline
      objects: only-multiline
      functions: only-multiline
